name: 'C++ CI'
on:
  push:
    branches:
      - master
      - feature/github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libboost-test-dev -y
        
      - name: Configure CMake
        run: cmake . -DPATCH_VERSION=${{ github.run_number }}
        working-directory: ./01

      - name: Build
        run: cmake --build .
        working-directory: ./01

      - name: Test
        run: cmake --build . --target test
        working-directory: ./01

      - name: Package
        run: cmake --build . --target package
        working-directory: ./01
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          files: ./helloworld-0.0.${{ github.run_number }}-Linux.deb
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}